// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJ_PnNJCnqYNg2C1_MA3Z39RbpuuQuWR0',
    appId: '1:959939021205:web:c4efd62b1dbe2e6b318e9c',
    messagingSenderId: '959939021205',
    projectId: 'lunar-621c3',
    authDomain: 'lunar-621c3.firebaseapp.com',
    storageBucket: 'lunar-621c3.firebasestorage.app',
    measurementId: 'G-BSFVSY3HTY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNgAcsxHcuFmPGp5Ev0fTbWNDTuXBo6ok',
    appId: '1:959939021205:android:2d56f5f65077ba7b318e9c',
    messagingSenderId: '959939021205',
    projectId: 'lunar-621c3',
    storageBucket: 'lunar-621c3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCi9U3HqDnpC9WWTex8VSTOXjzecw8mh2Q',
    appId: '1:959939021205:ios:9b39b82529a5f70c318e9c',
    messagingSenderId: '959939021205',
    projectId: 'lunar-621c3',
    storageBucket: 'lunar-621c3.firebasestorage.app',
    iosBundleId: 'com.example.lunar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCi9U3HqDnpC9WWTex8VSTOXjzecw8mh2Q',
    appId: '1:959939021205:ios:9b39b82529a5f70c318e9c',
    messagingSenderId: '959939021205',
    projectId: 'lunar-621c3',
    storageBucket: 'lunar-621c3.firebasestorage.app',
    iosBundleId: 'com.example.lunar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJ_PnNJCnqYNg2C1_MA3Z39RbpuuQuWR0',
    appId: '1:959939021205:web:19325ccc8a7ad5ff318e9c',
    messagingSenderId: '959939021205',
    projectId: 'lunar-621c3',
    authDomain: 'lunar-621c3.firebaseapp.com',
    storageBucket: 'lunar-621c3.firebasestorage.app',
    measurementId: 'G-JEP2YHYTY6',
  );
}
